USE SAKILA;
SHOW TABLES;
SELECT * FROM ACTOR;
SELECT FIRST_NAME, LAST_NAME FROM ACTOR;
SELECT * FROM CITY;
SELECT DISTINCT CITY FROM CITY;
SELECT LAST_UPDATE, CITY FROM CITY;
SELECT fIRST_NAME FROM ACTOR;
SELECT DISTINCT * FROM ACTOR;
SELECT TITLE AS 'TITULO OSTIAS', DESCRIPTION AS 'VIVA ESPAÑA' FROM FILM; 
SELECT LAST_NAME, FIRST_NAME FROM ACTOR WHERE LAST_NAME = 'ALLEN';
SELECT * FROM FILM WHERE LENGTH>=170 ORDER BY LENGTH DESC;
SELECT * FROM FILM WHERE LENGTH>=170 ORDER BY LENGTH ASC;
SELECT * FROM FILM WHERE LENGTH>90 AND RENTAL_RATE<=3;
SELECT * FROM FILM WHERE LENGTH<90 OR RENTAL_RATE>=3;
SELECT * FROM CUSTOMER WHERE(FIRST_NAME='JONH' OR LAST_NAME='SMITH' ) AND ACTIVE=1;
SELECT * FROM ACTOR WHERE LAST_NAME<>'ALLEN';
SELECT * FROM CUSTOMER WHERE NOT((FIRST_NAME='JONH' OR LAST_NAME='SMITH' ) AND ACTIVE=1);
SELECT * FROM FILM WHERE TITLE LIKE '%LOVE%';
SELECT * FROM FILM WHERE TITLE LIKE 'LOVE%';
SELECT * FROM FILM WHERE TITLE LIKE '%LOVE';
SELECT * FROM ACTOR WHERE LAST_NAME IN ('ALLEN','MCCONAUGHEY','PALTROW');
SELECT TITLE FROM FILM WHERE RENTAL_RATE>=0.5 AND RENTAL_RATE>=2.5;
SELECT TITLE FROM FILM WHERE RENTAL_RATE BETWEEN 0.5 AND 2.5;
(SELECT TITLE AS 'TITULO' FROM FILM WHERE TITLE LIKE '%RUN%' ORDER BY TITLE ASC) UNION (SELECT NAME FROM CATEGORY);
/* CON UNION SE MUESTRAN REGISTROS UNICOS ES DECIR QUE SI ENTRE LA UNION DE CAMPOS TITULO Y NAME HAY DOS REGISTROS IGUALES, SOLO APARECERA UNO EN LA TABLA*/
/* SI PONEMOS UNION ALL AÑADE TODOS LOS REGISTROS INCLUSO LOS REPETITIVOS*/
(SELECT TITLE AS 'TITULO' FROM FILM WHERE TITLE LIKE '%RUN%') UNION ALL (SELECT NAME FROM CATEGORY )ORDER BY TITULO ASC;
SELECT TITLE AS 'TITULO' FROM FILM WHERE FILM_ID IN (SELECT FILM_ID FROM FILM_CATEGORY WHERE CATEGORY_ID IN(SELECT CATEGORY_ID FROM CATEGORY WHERE NAME='COMEDY'));
SELECT LCASE(TITLE) FROM FILM;
SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) FROM ACTOR;
SELECT CONCAT(FIRST_NAME,' ',LCASE(LAST_NAME)) FROM ACTOR;
SELECT TITLE AS 'TITULO', RENTAL_RATE*0.75 AS 'PRECIO EN EUROS' FROM FILM;
SELECT COUNT(*) AS 'CLIENTES ACTIVOS' FROM CUSTOMER WHERE ACTIVE=1;
/*SELECT * FROM CUSTOMER WHERE ACTIVE=1;*/
SELECT MAX(RENTAL_RATE) AS 'PRECIO MAXIMO' FROM FILM; 
SELECT MIN(RENTAL_RATE) AS 'PRECIO MINIMO' FROM FILM; 
SELECT MIN(RENTAL_RATE) AS 'PRECIO MINIMO', MAX(RENTAL_RATE) AS 'PRECIO MAXIMO' FROM FILM; 
SELECT AVG(RENTAL_RATE) AS 'PRECIO MEDIO' FROM FILM;
SELECT COUNT(*), RENTAL_RATE FROM FILM GROUP BY RENTAL_RATE;
SELECT COUNT(*), RENTAL_RATE FROM FILM WHERE REPLACEMENT_COST<=20 GROUP BY RENTAL_RATE HAVING COUNT(*)>165 ORDER BY RENTAL_RATE DESC;
SELECT first_name, last_name, address FROM customer c, address a WHERE c.address_id = a.address_id;/* ES COMO UN JOIN PERO NO TIENE QUE HABER NINGUNA TABLA DE CONEXIÓN ENTRE ELLAS TIPO N:M, TIENE QUE SER CONEXIÓN DIRECTA ENTRE AMBAS TABLAS*/
SELECT first_name, last_name, address FROM customer c INNER JOIN address a ON c.address_id = a.address_id;
SELECT first_name, last_name, address FROM customer c LEFT JOIN address a ON c.address_id = a.address_id;
SELECT first_name, last_name, address FROM customer c RIGHT JOIN address a ON c.address_id = a.address_id;
INSERT INTO ACTOR (ACTOR_ID, LAST_NAME, FIRST_NAME, LAST_UPDATE)
VALUES(525, 'MARSUPIAL', 'AÑEZITO', '2018-03-06');
SELECT * FROM ACTOR WHERE ACTOR_ID=525;
UPDATE ACTOR
SET FIRST_NAME='XIQUITO', LAST_NAME='DE LA CALSADA PISHA'
WHERE ACTOR_ID= 525;
SELECT * FROM ACTOR WHERE ACTOR_ID=525;
DELETE FROM ACTOR
WHERE ACTOR_ID=525;
SELECT * FROM ACTOR WHERE ACTOR_ID=525;
SELECT * FROM ACTOR;

