-- MySQL Script generated by MySQL Workbench
-- Wed Feb 19 00:32:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `Biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `Biblioteca` ;

-- -----------------------------------------------------
-- Table `Biblioteca`.`Socios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Socios` (
  `id_Codigo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `DNI` VARCHAR(9) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  `Correo` VARCHAR(60) NOT NULL,
  `Direccion` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_Codigo`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteca`.`Prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Prestamos` (
  `id_Prestamos` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Vencimiento` DATE NOT NULL,
  `Entrega` DATE NOT NULL,
  `Socios_id_Codigo` INT NOT NULL,
  PRIMARY KEY (`id_Prestamos`),
  INDEX `fk_Prestamos_Socios_idx` (`Socios_id_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamos_Socios`
    FOREIGN KEY (`Socios_id_Codigo`)
    REFERENCES `Biblioteca`.`Socios` (`id_Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteca`.`Volumenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Volumenes` (
  `id_Volumenes` INT NOT NULL AUTO_INCREMENT,
  `Deterioro` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_Volumenes`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteca`.`Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Libros` (
  `id_ISBN` VARCHAR(20) NOT NULL,
  `Editorial` VARCHAR(100) NOT NULL,
  `Editorial_Edicion` VARCHAR(100) NOT NULL,
  `Año` DATE NOT NULL,
  `Titulo` VARCHAR(150) NOT NULL,
  `Año_Edicion` DATE NOT NULL,
  `Volumenes_id_Volumenes` INT NOT NULL,
  PRIMARY KEY (`id_ISBN`),
  INDEX `fk_Libros_Volumenes1_idx` (`Volumenes_id_Volumenes` ASC) VISIBLE,
  CONSTRAINT `fk_Libros_Volumenes1`
    FOREIGN KEY (`Volumenes_id_Volumenes`)
    REFERENCES `Biblioteca`.`Volumenes` (`id_Volumenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteca`.`Autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Autores` (
  `id_Autores` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_Autores`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteca`.`Prestamos_has_Volumenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Prestamos_has_Volumenes` (
  `Prestamos_id_Prestamos` INT NOT NULL,
  `Volumenes_id_Volumenes` INT NOT NULL,
  PRIMARY KEY (`Prestamos_id_Prestamos`, `Volumenes_id_Volumenes`),
  INDEX `fk_Prestamos_has_Volumenes_Volumenes1_idx` (`Volumenes_id_Volumenes` ASC) VISIBLE,
  INDEX `fk_Prestamos_has_Volumenes_Prestamos1_idx` (`Prestamos_id_Prestamos` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamos_has_Volumenes_Prestamos1`
    FOREIGN KEY (`Prestamos_id_Prestamos`)
    REFERENCES `Biblioteca`.`Prestamos` (`id_Prestamos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamos_has_Volumenes_Volumenes1`
    FOREIGN KEY (`Volumenes_id_Volumenes`)
    REFERENCES `Biblioteca`.`Volumenes` (`id_Volumenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteca`.`Autores_has_Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Autores_has_Libros` (
  `Autores_id_Autores` INT NOT NULL,
  `Libros_ISBN` VARCHAR(20) NOT NULL,  -- Cambiado de INT a VARCHAR(20)
  PRIMARY KEY (`Autores_id_Autores`, `Libros_ISBN`),
  INDEX `fk_Autores_has_Libros_Libros1_idx` (`Libros_ISBN` ASC) VISIBLE,
  INDEX `fk_Autores_has_Libros_Autores1_idx` (`Autores_id_Autores` ASC) VISIBLE,
  CONSTRAINT `fk_Autores_has_Libros_Autores1`
    FOREIGN KEY (`Autores_id_Autores`)
    REFERENCES `Biblioteca`.`Autores` (`id_Autores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autores_has_Libros_Libros1`
    FOREIGN KEY (`Libros_ISBN`)
    REFERENCES `Biblioteca`.`Libros` (`id_ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Create user and assign privileges
CREATE USER 'MiConexion' IDENTIFIED BY 'Javitolb1996';

-- Grant necessary privileges
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON `Biblioteca`.* TO 'MiConexion';
GRANT EXECUTE ON `Biblioteca`.* TO 'MiConexion'; -- Corrected line for EXECUTE privilege

-- Optionally, if you want to explicitly grant EXECUTE on specific routines, use the following:
-- GRANT EXECUTE ON PROCEDURE `Biblioteca`.`nombre_del_procedimiento` TO 'MiConexion';
-- GRANT EXECUTE ON FUNCTION `Biblioteca`.`nombre_de_la_funcion` TO 'MiConexion';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;