-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 17:36:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RedSocial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RedSocial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RedSocial` DEFAULT CHARACTER SET utf8 ;
USE `RedSocial` ;

-- -----------------------------------------------------
-- Table `RedSocial`.`Lista_bloqueados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial`.`Lista_bloqueados` (
  `id_Lista_bloqueados` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nº_Bloqueados` INT UNSIGNED NOT NULL,
  `Nombre_lista` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_Lista_bloqueados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial`.`Usuarios` (
  `id_Usuarios` VARCHAR(70) NOT NULL,
  `Descripion` VARCHAR(200) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Lista_bloqueados_id_Lista_bloqueados` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Usuarios`),
  INDEX `fk_Usuarios_Lista_bloqueados1_idx` (`Lista_bloqueados_id_Lista_bloqueados` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Lista_bloqueados1`
    FOREIGN KEY (`Lista_bloqueados_id_Lista_bloqueados`)
    REFERENCES `RedSocial`.`Lista_bloqueados` (`id_Lista_bloqueados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial`.`Grupos_de_contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial`.`Grupos_de_contactos` (
  `id_Grupos_de_contactos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Numero_contactos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Grupos_de_contactos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial`.`Comentarios` (
  `id_Comentarios` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Texto` LONGTEXT NOT NULL,
  `Imagen(ruta)` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_Comentarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial`.`Perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial`.`Perfiles` (
  `id_Perfiles` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  `Usuarios_id_Usuarios` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id_Perfiles`),
  INDEX `fk_Perfiles_Usuarios1_idx` (`Usuarios_id_Usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Perfiles_Usuarios1`
    FOREIGN KEY (`Usuarios_id_Usuarios`)
    REFERENCES `RedSocial`.`Usuarios` (`id_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial`.`Perfiles_normales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial`.`Perfiles_normales` (
  `id_Perfiles_normales` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(170) NOT NULL,
  `Email` VARCHAR(170) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  `Perfiles_id_Perfiles` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Perfiles_normales`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  INDEX `fk_Perfiles_normales_Perfiles1_idx` (`Perfiles_id_Perfiles` ASC) VISIBLE,
  CONSTRAINT `fk_Perfiles_normales_Perfiles1`
    FOREIGN KEY (`Perfiles_id_Perfiles`)
    REFERENCES `RedSocial`.`Perfiles` (`id_Perfiles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial`.`Usuarios_has_Grupos_de_contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial`.`Usuarios_has_Grupos_de_contactos` (
  `Usuarios_id_Usuarios` VARCHAR(70) NOT NULL,
  `Grupos_de_contactos_id_Grupos_de_contactos` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Usuarios_id_Usuarios`, `Grupos_de_contactos_id_Grupos_de_contactos`),
  INDEX `fk_Usuarios_has_Grupos_de_contactos_Grupos_de_contactos1_idx` (`Grupos_de_contactos_id_Grupos_de_contactos` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Grupos_de_contactos_Usuarios_idx` (`Usuarios_id_Usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Grupos_de_contactos_Usuarios`
    FOREIGN KEY (`Usuarios_id_Usuarios`)
    REFERENCES `RedSocial`.`Usuarios` (`id_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Grupos_de_contactos_Grupos_de_contactos1`
    FOREIGN KEY (`Grupos_de_contactos_id_Grupos_de_contactos`)
    REFERENCES `RedSocial`.`Grupos_de_contactos` (`id_Grupos_de_contactos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial`.`Comentarios_has_Grupos_de_contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial`.`Comentarios_has_Grupos_de_contactos` (
  `Comentarios_id_Comentarios` INT UNSIGNED NOT NULL,
  `Grupos_de_contactos_id_Grupos_de_contactos` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Comentarios_id_Comentarios`, `Grupos_de_contactos_id_Grupos_de_contactos`),
  INDEX `fk_Comentarios_has_Grupos_de_contactos_Grupos_de_contactos1_idx` (`Grupos_de_contactos_id_Grupos_de_contactos` ASC) VISIBLE,
  INDEX `fk_Comentarios_has_Grupos_de_contactos_Comentarios1_idx` (`Comentarios_id_Comentarios` ASC) VISIBLE,
  CONSTRAINT `fk_Comentarios_has_Grupos_de_contactos_Comentarios1`
    FOREIGN KEY (`Comentarios_id_Comentarios`)
    REFERENCES `RedSocial`.`Comentarios` (`id_Comentarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_has_Grupos_de_contactos_Grupos_de_contactos1`
    FOREIGN KEY (`Grupos_de_contactos_id_Grupos_de_contactos`)
    REFERENCES `RedSocial`.`Grupos_de_contactos` (`id_Grupos_de_contactos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial`.`Usuarios_has_Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial`.`Usuarios_has_Comentarios` (
  `Usuarios_id_Usuarios` VARCHAR(70) NOT NULL,
  `Comentarios_id_Comentarios` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Usuarios_id_Usuarios`, `Comentarios_id_Comentarios`),
  INDEX `fk_Usuarios_has_Comentarios_Comentarios1_idx` (`Comentarios_id_Comentarios` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Comentarios_Usuarios1_idx` (`Usuarios_id_Usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Comentarios_Usuarios1`
    FOREIGN KEY (`Usuarios_id_Usuarios`)
    REFERENCES `RedSocial`.`Usuarios` (`id_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Comentarios_Comentarios1`
    FOREIGN KEY (`Comentarios_id_Comentarios`)
    REFERENCES `RedSocial`.`Comentarios` (`id_Comentarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial`.`Usuarios_has_Lista_bloqueados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial`.`Usuarios_has_Lista_bloqueados` (
  `Usuarios_id_Usuarios` VARCHAR(70) NOT NULL,
  `Lista_bloqueados_id_Lista_bloqueados` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Usuarios_id_Usuarios`, `Lista_bloqueados_id_Lista_bloqueados`),
  INDEX `fk_Usuarios_has_Lista_bloqueados_Lista_bloqueados1_idx` (`Lista_bloqueados_id_Lista_bloqueados` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Lista_bloqueados_Usuarios1_idx` (`Usuarios_id_Usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Lista_bloqueados_Usuarios1`
    FOREIGN KEY (`Usuarios_id_Usuarios`)
    REFERENCES `RedSocial`.`Usuarios` (`id_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Lista_bloqueados_Lista_bloqueados1`
    FOREIGN KEY (`Lista_bloqueados_id_Lista_bloqueados`)
    REFERENCES `RedSocial`.`Lista_bloqueados` (`id_Lista_bloqueados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
