-- MySQL Script generated by MySQL Workbench
-- Tue Feb 18 19:47:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Institutos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Institutos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Institutos` DEFAULT CHARACTER SET utf8 ;
USE `Institutos` ;

-- -----------------------------------------------------
-- Table `Institutos`.`Imparticiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Institutos`.`Imparticiones` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Institutos`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Institutos`.`Alumnos` (
  `DNI` VARCHAR(9) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellidos` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(15) NULL,
  `Edad` INT NOT NULL,
  `Imparticiones_Codigo` INT NOT NULL,
  PRIMARY KEY (`DNI`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE,
  INDEX `fk_Alumnos_Imparticiones1_idx` (`Imparticiones_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Alumnos_Imparticiones1`
    FOREIGN KEY (`Imparticiones_Codigo`)
    REFERENCES `Institutos`.`Imparticiones` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Institutos`.`Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Institutos`.`Empresas` (
  `CIF` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(15) NULL,
  PRIMARY KEY (`CIF`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE,
  UNIQUE INDEX `Direccion_UNIQUE` (`Direccion` ASC) VISIBLE,
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Institutos`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Institutos`.`Cursos` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `Programa` VARCHAR(700) NOT NULL,
  `Titulo` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `Titulo_UNIQUE` (`Titulo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Institutos`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Institutos`.`Profesores` (
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellidos` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  `Imparticiones_Codigo` INT NOT NULL,
  PRIMARY KEY (`DNI`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE,
  INDEX `fk_Profesores_Imparticiones1_idx` (`Imparticiones_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Profesores_Imparticiones1`
    FOREIGN KEY (`Imparticiones_Codigo`)
    REFERENCES `Institutos`.`Imparticiones` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Institutos`.`Alumnos_has_Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Institutos`.`Alumnos_has_Empresas` (
  `Alumnos_DNI` VARCHAR(9) NOT NULL,
  `Empresas_CIF` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Alumnos_DNI`, `Empresas_CIF`),
  INDEX `fk_Alumnos_has_Empresas_Empresas1_idx` (`Empresas_CIF` ASC) VISIBLE,
  INDEX `fk_Alumnos_has_Empresas_Alumnos_idx` (`Alumnos_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Alumnos_has_Empresas_Alumnos`
    FOREIGN KEY (`Alumnos_DNI`)
    REFERENCES `Institutos`.`Alumnos` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumnos_has_Empresas_Empresas1`
    FOREIGN KEY (`Empresas_CIF`)
    REFERENCES `Institutos`.`Empresas` (`CIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Institutos`.`Cursos_has_Imparticiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Institutos`.`Cursos_has_Imparticiones` (
  `Cursos_Codigo` INT NOT NULL,
  `Imparticiones_Codigo` INT NOT NULL,
  PRIMARY KEY (`Cursos_Codigo`, `Imparticiones_Codigo`),
  INDEX `fk_Cursos_has_Imparticiones_Imparticiones1_idx` (`Imparticiones_Codigo` ASC) VISIBLE,
  INDEX `fk_Cursos_has_Imparticiones_Cursos1_idx` (`Cursos_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Cursos_has_Imparticiones_Cursos1`
    FOREIGN KEY (`Cursos_Codigo`)
    REFERENCES `Institutos`.`Cursos` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_has_Imparticiones_Imparticiones1`
    FOREIGN KEY (`Imparticiones_Codigo`)
    REFERENCES `Institutos`.`Imparticiones` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
