-- MySQL Script generated by MySQL Workbench
-- Tue Feb 18 19:11:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Almacenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Almacenes` (
  `id_Almacen` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(300) NOT NULL,
  `Direccion` VARCHAR(150) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_Almacen`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estanterias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estanterias` (
  `id_Estanterias` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Almacenes_id_Almacen` INT NOT NULL,
  PRIMARY KEY (`id_Estanterias`),
  INDEX `fk_Estanterias_Almacenes1_idx` (`Almacenes_id_Almacen` ASC) VISIBLE,
  CONSTRAINT `fk_Estanterias_Almacenes1`
    FOREIGN KEY (`Almacenes_id_Almacen`)
    REFERENCES `mydb`.`Almacenes` (`id_Almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piezas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piezas` (
  `id_Piezas` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `Estanterias_id_Estanterias` INT NOT NULL,
  PRIMARY KEY (`id_Piezas`),
  INDEX `fk_Piezas_Estanterias1_idx` (`Estanterias_id_Estanterias` ASC) VISIBLE,
  CONSTRAINT `fk_Piezas_Estanterias1`
    FOREIGN KEY (`Estanterias_id_Estanterias`)
    REFERENCES `mydb`.`Estanterias` (`id_Estanterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piezas_Compuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piezas_Compuestas` (
  `id_Piezas_Compuestas` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Composicion` VARCHAR(300) NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `Estanterias_id_Estanterias` INT NOT NULL,
  PRIMARY KEY (`id_Piezas_Compuestas`),
  INDEX `fk_Piezas_Compuestas_Estanterias1_idx` (`Estanterias_id_Estanterias` ASC) VISIBLE,
  CONSTRAINT `fk_Piezas_Compuestas_Estanterias1`
    FOREIGN KEY (`Estanterias_id_Estanterias`)
    REFERENCES `mydb`.`Estanterias` (`id_Estanterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piezas_Compuestas_has_Piezas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piezas_Compuestas_has_Piezas` (
  `Piezas_Compuestas_id_Piezas_Compuestas` INT NOT NULL,
  `Piezas_id_Piezas` INT NOT NULL,
  PRIMARY KEY (`Piezas_Compuestas_id_Piezas_Compuestas`, `Piezas_id_Piezas`),
  INDEX `fk_Piezas_Compuestas_has_Piezas_Piezas1_idx` (`Piezas_id_Piezas` ASC) VISIBLE,
  INDEX `fk_Piezas_Compuestas_has_Piezas_Piezas_Compuestas1_idx` (`Piezas_Compuestas_id_Piezas_Compuestas` ASC) VISIBLE,
  CONSTRAINT `fk_Piezas_Compuestas_has_Piezas_Piezas_Compuestas1`
    FOREIGN KEY (`Piezas_Compuestas_id_Piezas_Compuestas`)
    REFERENCES `mydb`.`Piezas_Compuestas` (`id_Piezas_Compuestas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Piezas_Compuestas_has_Piezas_Piezas1`
    FOREIGN KEY (`Piezas_id_Piezas`)
    REFERENCES `mydb`.`Piezas` (`id_Piezas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
